# Generated by Django 3.2.10 on 2023-08-09 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('Name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='item.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
