# Generated by Django 3.2.10 on 2023-08-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20230809_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('Name',), 'verbose_name_plural': 'Books'},
        ),
    ]
