# Generated by Django 3.2.10 on 2023-08-14 04:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0004_books_book_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('Name',), 'verbose_name_plural': 'Item'},
        ),
    ]
